service: 'kickboard-death'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: stage
  lambdaHashingVersion: '20201221'
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    includeModules: true
    packager: 'yarn'
    packagerOptions:
      noFrozenLockfile: true

functions:
  app:
    handler: src/index.handler
    events:
      - schedule:
          enabled: true
          rate: rate(30 minutes)
